/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-inter)', 'sans-serif'],
        serif: ['var(--font-crimson-text)', 'serif'],
        urdu: ['var(--font-noto-nastaliq-urdu)', 'serif'],
      },
      colors: {
        paper: {
          50: '#f8f6f3',
          100: '#f0ede8',
          200: '#e8e3dc',
          300: '#ddd8d1',
          400: '#d4d1cc',
          500: '#c4bfb8',
          600: '#b8b3ab',
          700: '#a39a8f',
          800: '#6b5b5b',
          900: '#2c2c2c',
          950: '#1a1a1a',
        },
        accent: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        literary: {
          gold: '#d4af37',
          'gold-light': '#f4e4a6',
          'gold-dark': '#b8941f',
          sage: '#9caf88',
          'sage-light': '#c4d1b0',
          'sage-dark': '#7a8f6b',
          burgundy: '#722f37',
          'burgundy-light': '#a8515a',
          'burgundy-dark': '#5a252b',
          // Enhanced literary palette
          'parchment': '#f7f3e9',
          'parchment-dark': '#2d2a24',
          'ink': '#1a1a1a',
          'ink-light': '#4a4a4a',
          'sepia': '#8b7355',
          'sepia-light': '#b8a082',
          'sepia-dark': '#6b5a42',
          'emerald': '#2d5a27',
          'emerald-light': '#4a7c59',
          'emerald-dark': '#1e3d1a',
        },
        reading: {
          // Optimized colors for reading experience
          'text-primary': '#2c2c2c',
          'text-secondary': '#5a5a5a',
          'text-muted': '#8a8a8a',
          'bg-primary': '#fefefe',
          'bg-secondary': '#f8f8f8',
          'bg-accent': '#f0f0f0',
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'slide-down': 'slideDown 0.5s ease-out',
        'slide-left': 'slideLeft 0.5s ease-out',
        'slide-right': 'slideRight 0.5s ease-out',
        'scale-in': 'scaleIn 0.3s ease-out',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce 3s infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideLeft: {
          '0%': { transform: 'translateX(20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideRight: {
          '0%': { transform: 'translateX(-20px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      backgroundImage: {
        'paper-texture': "url('/images/paper-texture.png')",
        'paper-pattern': "url('/images/paper-pattern.png')",
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      boxShadow: {
        'inner-light': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)',
        'inner-medium': 'inset 0 4px 6px 0 rgba(0, 0, 0, 0.1)',
        'elegant': '0 4px 12px rgba(0, 0, 0, 0.08), 0 1px 3px rgba(0, 0, 0, 0.1)',
        'elegant-dark': '0 4px 12px rgba(0, 0, 0, 0.15), 0 1px 3px rgba(0, 0, 0, 0.2)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.1), 0 4px 16px rgba(0, 0, 0, 0.05)',
        'glass-dark': '0 8px 32px rgba(0, 0, 0, 0.3), 0 4px 16px rgba(0, 0, 0, 0.15)',
        'literary': '0 10px 40px rgba(212, 175, 55, 0.15), 0 4px 16px rgba(212, 175, 55, 0.1)',
        'soft': '0 2px 8px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.06)',
        'medium': '0 4px 16px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.1)',
        'strong': '0 8px 24px rgba(0, 0, 0, 0.12), 0 4px 8px rgba(0, 0, 0, 0.14)',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: '65ch',
            color: 'inherit',
            a: {
              color: 'inherit',
              opacity: 0.8,
              '&:hover': {
                opacity: 1,
                color: 'var(--tw-prose-links)',
              },
              textDecoration: 'underline',
              textDecorationColor: 'rgba(125, 125, 125, 0.3)',
            },
            b: { color: 'inherit' },
            strong: { color: 'inherit' },
            em: { color: 'inherit' },
            h1: { color: 'inherit' },
            h2: { color: 'inherit' },
            h3: { color: 'inherit' },
            h4: { color: 'inherit' },
            code: { color: 'inherit' },
          },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
