
// Audiobook data for Crime and Punishment
// Generated by audiobook-integration script

import { Book, AudioChapter } from '@/types';

export const crimeandpunishmentdostoevskyAudiobookData = {
  // Enable audiobook features
  hasAudio: true,
  isAudiobook: true,
  audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/full.mp3',
  audioDuration: 72000, // 20 hours
  narrator: 'LibriVox Community',
  audioQuality: 'high' as const,
  
  // Chapter-based audio files (update with actual chapter data)
  audioChapters: [
        {
      id: 'chapter-1',
      title: 'Chapter 1', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-01.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 0 // Update with actual start time
    },
    {
      id: 'chapter-2',
      title: 'Chapter 2', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-02.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 2571 // Update with actual start time
    },
    {
      id: 'chapter-3',
      title: 'Chapter 3', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-03.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 5143 // Update with actual start time
    },
    {
      id: 'chapter-4',
      title: 'Chapter 4', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-04.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 7714 // Update with actual start time
    },
    {
      id: 'chapter-5',
      title: 'Chapter 5', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-05.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 10286 // Update with actual start time
    },
    {
      id: 'chapter-6',
      title: 'Chapter 6', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-06.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 12857 // Update with actual start time
    },
    {
      id: 'chapter-7',
      title: 'Chapter 7', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-07.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 15429 // Update with actual start time
    },
    {
      id: 'chapter-8',
      title: 'Chapter 8', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-08.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 18000 // Update with actual start time
    },
    {
      id: 'chapter-9',
      title: 'Chapter 9', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-09.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 20571 // Update with actual start time
    },
    {
      id: 'chapter-10',
      title: 'Chapter 10', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-10.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 23143 // Update with actual start time
    },
    {
      id: 'chapter-11',
      title: 'Chapter 11', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-11.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 25714 // Update with actual start time
    },
    {
      id: 'chapter-12',
      title: 'Chapter 12', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-12.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 28286 // Update with actual start time
    },
    {
      id: 'chapter-13',
      title: 'Chapter 13', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-13.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 30857 // Update with actual start time
    },
    {
      id: 'chapter-14',
      title: 'Chapter 14', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-14.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 33429 // Update with actual start time
    },
    {
      id: 'chapter-15',
      title: 'Chapter 15', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-15.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 36000 // Update with actual start time
    },
    {
      id: 'chapter-16',
      title: 'Chapter 16', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-16.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 38571 // Update with actual start time
    },
    {
      id: 'chapter-17',
      title: 'Chapter 17', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-17.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 41143 // Update with actual start time
    },
    {
      id: 'chapter-18',
      title: 'Chapter 18', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-18.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 43714 // Update with actual start time
    },
    {
      id: 'chapter-19',
      title: 'Chapter 19', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-19.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 46286 // Update with actual start time
    },
    {
      id: 'chapter-20',
      title: 'Chapter 20', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-20.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 48857 // Update with actual start time
    },
    {
      id: 'chapter-21',
      title: 'Chapter 21', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-21.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 51429 // Update with actual start time
    },
    {
      id: 'chapter-22',
      title: 'Chapter 22', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-22.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 54000 // Update with actual start time
    },
    {
      id: 'chapter-23',
      title: 'Chapter 23', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-23.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 56571 // Update with actual start time
    },
    {
      id: 'chapter-24',
      title: 'Chapter 24', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-24.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 59143 // Update with actual start time
    },
    {
      id: 'chapter-25',
      title: 'Chapter 25', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-25.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 61714 // Update with actual start time
    },
    {
      id: 'chapter-26',
      title: 'Chapter 26', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-26.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 64286 // Update with actual start time
    },
    {
      id: 'chapter-27',
      title: 'Chapter 27', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-27.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 66857 // Update with actual start time
    },
    {
      id: 'chapter-28',
      title: 'Chapter 28', // Update with actual chapter title
      audioUrl: '/audio/books/crime-and-punishment-dostoevsky/en/chapter-28.mp3',
      duration: 2571, // Estimated duration - update with actual
      startTime: 69429 // Update with actual start time
    }
  ] as AudioChapter[]
};

// Instructions for implementation:
// 1. Download audiobook files from: https://librivox.org/crime-and-punishment-by-fyodor-dostoyevsky/
// 2. Process and place files in: public/audio/books/crime-and-punishment-dostoevsky/en/
// 3. Update chapter data with actual durations and titles
// 4. Merge this data with the existing book object in the data file
