
// Audiobook data for Pride and Prejudice
// Generated by audiobook-integration script

import { Book, AudioChapter } from '@/types';

export const prideandprejudiceAudiobookData = {
  // Enable audiobook features
  hasAudio: true,
  isAudiobook: true,
  audioUrl: '/audio/books/pride-and-prejudice/en/full.mp3',
  audioDuration: 43200, // 12 hours
  narrator: 'Karen Savage',
  audioQuality: 'high' as const,
  
  // Chapter-based audio files (update with actual chapter data)
  audioChapters: [
        {
      id: 'chapter-1',
      title: 'Chapter 1', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-01.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 0 // Update with actual start time
    },
    {
      id: 'chapter-2',
      title: 'Chapter 2', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-02.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 708 // Update with actual start time
    },
    {
      id: 'chapter-3',
      title: 'Chapter 3', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-03.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 1416 // Update with actual start time
    },
    {
      id: 'chapter-4',
      title: 'Chapter 4', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-04.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 2125 // Update with actual start time
    },
    {
      id: 'chapter-5',
      title: 'Chapter 5', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-05.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 2833 // Update with actual start time
    },
    {
      id: 'chapter-6',
      title: 'Chapter 6', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-06.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 3541 // Update with actual start time
    },
    {
      id: 'chapter-7',
      title: 'Chapter 7', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-07.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 4249 // Update with actual start time
    },
    {
      id: 'chapter-8',
      title: 'Chapter 8', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-08.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 4957 // Update with actual start time
    },
    {
      id: 'chapter-9',
      title: 'Chapter 9', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-09.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 5666 // Update with actual start time
    },
    {
      id: 'chapter-10',
      title: 'Chapter 10', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-10.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 6374 // Update with actual start time
    },
    {
      id: 'chapter-11',
      title: 'Chapter 11', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-11.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 7082 // Update with actual start time
    },
    {
      id: 'chapter-12',
      title: 'Chapter 12', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-12.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 7790 // Update with actual start time
    },
    {
      id: 'chapter-13',
      title: 'Chapter 13', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-13.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 8498 // Update with actual start time
    },
    {
      id: 'chapter-14',
      title: 'Chapter 14', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-14.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 9207 // Update with actual start time
    },
    {
      id: 'chapter-15',
      title: 'Chapter 15', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-15.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 9915 // Update with actual start time
    },
    {
      id: 'chapter-16',
      title: 'Chapter 16', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-16.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 10623 // Update with actual start time
    },
    {
      id: 'chapter-17',
      title: 'Chapter 17', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-17.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 11331 // Update with actual start time
    },
    {
      id: 'chapter-18',
      title: 'Chapter 18', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-18.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 12039 // Update with actual start time
    },
    {
      id: 'chapter-19',
      title: 'Chapter 19', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-19.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 12748 // Update with actual start time
    },
    {
      id: 'chapter-20',
      title: 'Chapter 20', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-20.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 13456 // Update with actual start time
    },
    {
      id: 'chapter-21',
      title: 'Chapter 21', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-21.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 14164 // Update with actual start time
    },
    {
      id: 'chapter-22',
      title: 'Chapter 22', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-22.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 14872 // Update with actual start time
    },
    {
      id: 'chapter-23',
      title: 'Chapter 23', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-23.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 15580 // Update with actual start time
    },
    {
      id: 'chapter-24',
      title: 'Chapter 24', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-24.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 16289 // Update with actual start time
    },
    {
      id: 'chapter-25',
      title: 'Chapter 25', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-25.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 16997 // Update with actual start time
    },
    {
      id: 'chapter-26',
      title: 'Chapter 26', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-26.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 17705 // Update with actual start time
    },
    {
      id: 'chapter-27',
      title: 'Chapter 27', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-27.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 18413 // Update with actual start time
    },
    {
      id: 'chapter-28',
      title: 'Chapter 28', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-28.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 19121 // Update with actual start time
    },
    {
      id: 'chapter-29',
      title: 'Chapter 29', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-29.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 19830 // Update with actual start time
    },
    {
      id: 'chapter-30',
      title: 'Chapter 30', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-30.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 20538 // Update with actual start time
    },
    {
      id: 'chapter-31',
      title: 'Chapter 31', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-31.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 21246 // Update with actual start time
    },
    {
      id: 'chapter-32',
      title: 'Chapter 32', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-32.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 21954 // Update with actual start time
    },
    {
      id: 'chapter-33',
      title: 'Chapter 33', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-33.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 22662 // Update with actual start time
    },
    {
      id: 'chapter-34',
      title: 'Chapter 34', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-34.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 23370 // Update with actual start time
    },
    {
      id: 'chapter-35',
      title: 'Chapter 35', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-35.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 24079 // Update with actual start time
    },
    {
      id: 'chapter-36',
      title: 'Chapter 36', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-36.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 24787 // Update with actual start time
    },
    {
      id: 'chapter-37',
      title: 'Chapter 37', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-37.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 25495 // Update with actual start time
    },
    {
      id: 'chapter-38',
      title: 'Chapter 38', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-38.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 26203 // Update with actual start time
    },
    {
      id: 'chapter-39',
      title: 'Chapter 39', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-39.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 26911 // Update with actual start time
    },
    {
      id: 'chapter-40',
      title: 'Chapter 40', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-40.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 27620 // Update with actual start time
    },
    {
      id: 'chapter-41',
      title: 'Chapter 41', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-41.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 28328 // Update with actual start time
    },
    {
      id: 'chapter-42',
      title: 'Chapter 42', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-42.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 29036 // Update with actual start time
    },
    {
      id: 'chapter-43',
      title: 'Chapter 43', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-43.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 29744 // Update with actual start time
    },
    {
      id: 'chapter-44',
      title: 'Chapter 44', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-44.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 30452 // Update with actual start time
    },
    {
      id: 'chapter-45',
      title: 'Chapter 45', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-45.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 31161 // Update with actual start time
    },
    {
      id: 'chapter-46',
      title: 'Chapter 46', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-46.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 31869 // Update with actual start time
    },
    {
      id: 'chapter-47',
      title: 'Chapter 47', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-47.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 32577 // Update with actual start time
    },
    {
      id: 'chapter-48',
      title: 'Chapter 48', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-48.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 33285 // Update with actual start time
    },
    {
      id: 'chapter-49',
      title: 'Chapter 49', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-49.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 33993 // Update with actual start time
    },
    {
      id: 'chapter-50',
      title: 'Chapter 50', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-50.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 34702 // Update with actual start time
    },
    {
      id: 'chapter-51',
      title: 'Chapter 51', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-51.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 35410 // Update with actual start time
    },
    {
      id: 'chapter-52',
      title: 'Chapter 52', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-52.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 36118 // Update with actual start time
    },
    {
      id: 'chapter-53',
      title: 'Chapter 53', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-53.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 36826 // Update with actual start time
    },
    {
      id: 'chapter-54',
      title: 'Chapter 54', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-54.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 37534 // Update with actual start time
    },
    {
      id: 'chapter-55',
      title: 'Chapter 55', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-55.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 38243 // Update with actual start time
    },
    {
      id: 'chapter-56',
      title: 'Chapter 56', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-56.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 38951 // Update with actual start time
    },
    {
      id: 'chapter-57',
      title: 'Chapter 57', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-57.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 39659 // Update with actual start time
    },
    {
      id: 'chapter-58',
      title: 'Chapter 58', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-58.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 40367 // Update with actual start time
    },
    {
      id: 'chapter-59',
      title: 'Chapter 59', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-59.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 41075 // Update with actual start time
    },
    {
      id: 'chapter-60',
      title: 'Chapter 60', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-60.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 41784 // Update with actual start time
    },
    {
      id: 'chapter-61',
      title: 'Chapter 61', // Update with actual chapter title
      audioUrl: '/audio/books/pride-and-prejudice/en/chapter-61.mp3',
      duration: 708, // Estimated duration - update with actual
      startTime: 42492 // Update with actual start time
    }
  ] as AudioChapter[]
};

// Instructions for implementation:
// 1. Download audiobook files from: https://librivox.org/pride-and-prejudice-by-jane-austen/
// 2. Process and place files in: public/audio/books/pride-and-prejudice/en/
// 3. Update chapter data with actual durations and titles
// 4. Merge this data with the existing book object in the data file
