
// Audiobook data for The Notebook
// Generated by audiobook-integration script

import { Book, AudioChapter } from '@/types';

export const thenotebookAudiobookData = {
  // Enable audiobook features
  hasAudio: true,
  isAudiobook: true,
  audioUrl: '/audio/books/the-notebook/en/full.mp3',
  audioDuration: 25200, // 7 hours
  narrator: 'Professional Narrator',
  audioQuality: 'high' as const,
  
  // Chapter-based audio files (update with actual chapter data)
  audioChapters: [
        {
      id: 'chapter-1',
      title: 'Chapter 1', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-01.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 0 // Update with actual start time
    },
    {
      id: 'chapter-2',
      title: 'Chapter 2', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-02.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 2100 // Update with actual start time
    },
    {
      id: 'chapter-3',
      title: 'Chapter 3', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-03.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 4200 // Update with actual start time
    },
    {
      id: 'chapter-4',
      title: 'Chapter 4', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-04.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 6300 // Update with actual start time
    },
    {
      id: 'chapter-5',
      title: 'Chapter 5', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-05.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 8400 // Update with actual start time
    },
    {
      id: 'chapter-6',
      title: 'Chapter 6', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-06.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 10500 // Update with actual start time
    },
    {
      id: 'chapter-7',
      title: 'Chapter 7', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-07.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 12600 // Update with actual start time
    },
    {
      id: 'chapter-8',
      title: 'Chapter 8', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-08.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 14700 // Update with actual start time
    },
    {
      id: 'chapter-9',
      title: 'Chapter 9', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-09.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 16800 // Update with actual start time
    },
    {
      id: 'chapter-10',
      title: 'Chapter 10', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-10.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 18900 // Update with actual start time
    },
    {
      id: 'chapter-11',
      title: 'Chapter 11', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-11.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 21000 // Update with actual start time
    },
    {
      id: 'chapter-12',
      title: 'Chapter 12', // Update with actual chapter title
      audioUrl: '/audio/books/the-notebook/en/chapter-12.mp3',
      duration: 2100, // Estimated duration - update with actual
      startTime: 23100 // Update with actual start time
    }
  ] as AudioChapter[]
};

// Instructions for implementation:
// 1. Download audiobook files from: Licensed source
// 2. Process and place files in: public/audio/books/the-notebook/en/
// 3. Update chapter data with actual durations and titles
// 4. Merge this data with the existing book object in the data file
